%% SDPE MATLAB initialization script
% Project: DPS FSBB Common Control
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Notes:
%   Platform-independent FSBB topology, sensing, protection and control contract shared by all hardware and SIL targets.

%% Project metadata
DPS_FSBB_COMMON_SDPE_PROJECT_ID = 'dps_fsbb_common';

DPS_FSBB_COMMON_SDPE_PROJECT_SUITE = 'dps_fsbb';

DPS_FSBB_COMMON_SDPE_PROJECT_VERSION = '1.0.0';

DPS_FSBB_COMMON_SDPE_PROJECT_UPDATED_AT = '2026-07-18';

%% Hardware macros
BSC093N15NS5_ID = 'bsc093n15ns5';

BSC093N15NS5_SCHEMA = 'power_switch';

BSC093N15NS5_NAME = 'BSC093N15NS5';

% Power device part number.
BSC093N15NS5_PART_NUMBER = 'BSC093N15NS5';

% MOSFET, IGBT, GaN, SiC, etc.
BSC093N15NS5_DEVICE_TYPE = 'MOSFET';

% Drain-source or collector-emitter voltage rating.
BSC093N15NS5_VOLTAGE_RATING_V = 150.0;

% Current rating.
BSC093N15NS5_CURRENT_RATING_A = 55.0;

% On resistance.
BSC093N15NS5_RDSON_OHM = 0.0093;

% Single switch, dual switch, half bridge power block, etc.
BSC093N15NS5_CONFIGURATION = 'single';

% Maximum on resistance at the documented gate voltage.
BSC093N15NS5_RDSON_MAX_OHM = 0.0;

% Gate voltage associated with the resistance value.
BSC093N15NS5_GATE_VOLTAGE_V = 0.0;

% Typical total gate charge.
BSC093N15NS5_GATE_CHARGE_NC = 0.0;

% Manufacturer package name.
BSC093N15NS5_PACKAGE = 'unknown';

TMCS1133_B5A_ID = 'tmcs1133_b5a';

TMCS1133_B5A_SCHEMA = 'current_sensor';

TMCS1133_B5A_NAME = 'TMCS1133 B5A Hall Current Sensor';

% Main sensing IC or technology name.
TMCS1133_B5A_CHIP = 'TMCS1133B5A';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TMCS1133_B5A_SENSOR_TYPE = 'Hall';

% Nominal measurable current range.
TMCS1133_B5A_RANGE_A = 10.3;

% Minimum output voltage.
TMCS1133_B5A_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TMCS1133_B5A_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TMCS1133_B5A_BIAS_V = 1.65;

% Current sensor sensitivity.
TMCS1133_B5A_SENSITIVITY_MV_PER_A = 150.0;

% Typical small-signal bandwidth.
TMCS1133_B5A_BANDWIDTH_HZ = 300000.0;

% Sensor internal series resistance.
TMCS1133_B5A_INTERNAL_RESISTANCE_OHM = 0.0018;

% Current sensor sensitivity converted to V/A.
TMCS1133_B5A_SENSITIVITY_V_PER_A = TMCS1133_B5A_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A = TMCS1133_B5A_BIAS_V / TMCS1133_B5A_SENSITIVITY_V_PER_A;

LVFB_VDIV_150V_ID = 'lvfb_voltage_divider_150v';

LVFB_VDIV_150V_SCHEMA = 'voltage_sensor';

LVFB_VDIV_150V_NAME = 'LVFB 150V Voltage Divider';

% Main sensing IC or front-end topology.
LVFB_VDIV_150V_CHIP = 'AMC1311BDWVR + resistor divider';

% Nominal measurable voltage.
LVFB_VDIV_150V_RATED_VOLTAGE_V = 150.0;

% Output bias voltage.
LVFB_VDIV_150V_BIAS_V = 0.0;

% Voltage sensor sensitivity.
LVFB_VDIV_150V_SENSITIVITY_V_PER_V = 0.016129;

% Equivalent input resistance.
LVFB_VDIV_150V_INPUT_RESISTANCE_OHM = 915000.0;

% Approximate positive full scale voltage when biased at mid-supply.
LVFB_VDIV_150V_MAX_BY_BIAS_V = sdpe_select(LVFB_VDIV_150V_BIAS_V > 0.0, LVFB_VDIV_150V_BIAS_V / LVFB_VDIV_150V_SENSITIVITY_V_PER_V, LVFB_VDIV_150V_RATED_VOLTAGE_V);

GMP_LVFB_ID = 'gmp_lvfb_150_2ph_v2';

GMP_LVFB_SCHEMA = 'half_bridge';

GMP_LVFB_NAME = 'GMP LVFB 150V 2-Phase V2 Inverter Board';

% Board or module name.
GMP_LVFB_BOARD_NAME = 'GMP LVFB 2ph V6.1';

% Integrated gate driver part number.
GMP_LVFB_GATE_DRIVER = 'UCC21520DWR';

% Power MOSFET part number.
GMP_LVFB_MOSFET = 'BSC093N15NS5';

% On-board current sensing device.
GMP_LVFB_CURRENT_SENSOR_NAME = 'TMCS1133B5A';

% On-board voltage sensing device.
GMP_LVFB_VOLTAGE_SENSOR_NAME = 'AMC1311BDWVR';

% Number of half-bridge phases represented by this module.
GMP_LVFB_PHASE_COUNT = 2;

% Current measurement range exported by the current sensor sub component.
GMP_LVFB_MEASURED_CURRENT_RANGE_A = TMCS1133_B5A_RANGE_A;

% Maximum allowable DC bus voltage.
GMP_LVFB_VBUS_MAX_V = 120.0;

% Maximum instantaneous peak phase current.
GMP_LVFB_CURRENT_MAX_PEAK_A = 55.0;

% Maximum continuous RMS phase current.
GMP_LVFB_CURRENT_MAX_RMS_A = 35.0;

% Recommended hardware deadtime.
GMP_LVFB_DEADTIME_NS = 523.0;

% Current sensing signal bandwidth.
GMP_LVFB_CURRENT_BW_HZ = 300.0e3;

% Current sensor ADC bias voltage.
GMP_LVFB_CURRENT_BIAS_V = 1.65;

% Configured current sensitivity.
GMP_LVFB_CURRENT_SENSITIVITY = TMCS1133_B5A_SENSITIVITY_V_PER_A;

% ADC reference scale voltage.
GMP_LVFB_VOLTAGE_BASE_V = 3.3;

% Voltage sensing ADC bias voltage.
GMP_LVFB_VOLTAGE_BIAS_V = 0.0;

% Voltage sensing bandwidth.
GMP_LVFB_VOLTAGE_BW_HZ = 114.47e3;

% Default low-side voltage divider resistance.
GMP_LVFB_VOLTAGE_R_LOW_OHM = 15000.0;

% Default high-side voltage divider resistance.
GMP_LVFB_VOLTAGE_R_HIGH_OHM = 300000.0;

% Configured voltage sensing gain.
GMP_LVFB_VOLTAGE_SENSITIVITY = (15e3) / ((15e3) + ((300e3) * 3)) * 1.65;

% Configured maximum measurable voltage.
GMP_LVFB_VOLTAGE_MAX = 3.3 / ((15e3) / ((15e3) + ((300e3) * 3)) * 1.65);

% Optional local DC bus capacitance.
GMP_LVFB_BUS_CAPACITANCE_F = 0.0;

% Whether this module declares a local bus capacitor.
GMP_LVFB_HAS_LOCAL_BUS_CAP = GMP_LVFB_BUS_CAPACITANCE_F > 0.0;

%% Requirement bindings
% FSBB switching frequency.
PWM_FREQ = 20e3;

% SIL controller sample frequency.
CONTROLLER_FREQUENCY = 20e3;

% ADC reference voltage.
CTRL_ADC_VOLTAGE_REF = 3.3;

% Voltage per-unit base.
CTRL_VOLTAGE_BASE = 34.0;

% Current per-unit base.
CTRL_CURRENT_BASE = 14.14;

% Minimum load resistance.
FSBB_PARAM_RLOAD_MIN = 200.0;

% Input capacitance.
FSBB_PARAM_CIN = 440e-6;

% Output capacitance.
FSBB_PARAM_COUT = 440e-6;

% Output capacitor ESR.
FSBB_PARAM_COUT_ESR = 0.1;

% Main FSBB inductance.
FSBB_PARAM_L = 1.5e-3;

% Main inductor ESR.
FSBB_PARAM_L_ESR = 0.05;

% Input-voltage sensor sensitivity in V/V.
CTRL_FSBB_VIN_SENSITIVITY = GMP_LVFB_VOLTAGE_SENSITIVITY;

% Input-voltage sensor bias in V.
CTRL_FSBB_VIN_BIAS = GMP_LVFB_VOLTAGE_BIAS_V;

% Output-voltage sensor sensitivity in V/V.
CTRL_FSBB_VOUT_SENSITIVITY = GMP_LVFB_VOLTAGE_SENSITIVITY;

% Output-voltage sensor bias in V.
CTRL_FSBB_VOUT_BIAS = GMP_LVFB_VOLTAGE_BIAS_V;

% Boost-side output-current sensor sensitivity in V/A.
CTRL_FSBB_IOUT_SENSITIVITY = GMP_LVFB_CURRENT_SENSITIVITY;

% Boost-side output-current sensor bias in V.
CTRL_FSBB_IOUT_BIAS = GMP_LVFB_CURRENT_BIAS_V;

% Inductor-current sensor sensitivity in V/A.
CTRL_FSBB_IL_SENSITIVITY = GMP_LVFB_CURRENT_SENSITIVITY;

% Inductor-current sensor bias in V.
CTRL_FSBB_IL_BIAS = GMP_LVFB_CURRENT_BIAS_V;

% Maximum input voltage.
FSBB_INPUT_VOLTAGE_MAX = 60.0;

% Minimum input voltage.
FSBB_INPUT_VOLTAGE_MIN = 12.0;

% Nominal model source voltage.
FSBB_INPUT_VOLTAGE_NOMINAL = 30.0;

% Maximum output voltage.
FSBB_OUTPUT_VOLTAGE_MAX = 72.0;

% Minimum output voltage.
FSBB_OUTPUT_VOLTAGE_MIN = 3.0;

% Output current limit.
FSBB_OUTPUT_CURRENT_LIM = 10.0;

% Default voltage-loop command.
FSBB_DEFAULT_OUTPUT_VOLTAGE = 50.0;

% Default current limit.
FSBB_DEFAULT_CURRENT_LIMIT = 5.0;

% Maximum leg duty.
FSBB_DUTY_MAX = 0.99;

% Minimum leg duty.
FSBB_DUTY_MIN = 0.01;

% Positive inductor-current protection threshold.
FSBB_PROTECT_IL_MAX = 25.0;

% Negative inductor-current protection threshold.
FSBB_PROTECT_IL_MIN = -2.0;

% Open-loop equivalent voltage command.
FSBB_OPEN_LOOP_VOLTAGE_COMMAND = 12.0;

% Current-loop crossover frequency.
FSBB_CURRENT_LOOP_BANDWIDTH = 800.0;

% Voltage-loop crossover frequency.
FSBB_VOLTAGE_LOOP_BANDWIDTH = 40.0;

% Buck-to-transition boundary.
FSBB_TRANSITION_RATIO_LOW = 0.90;

% Transition-to-boost boundary.
FSBB_TRANSITION_RATIO_HIGH = 1.10;

% Compatibility setting used by the suite framework.
CTRL_SPLL_EPSILON = 0.005;

% ADC calibration timeout.
TIMEOUT_ADC_CALIB_MS = 3000;

% Voltage command ramp in pu/s.
FSBB_VOLTAGE_RAMP_PU_S = 1.0;

% Current command ramp in pu/s.
FSBB_CURRENT_RAMP_PU_S = 1.0;

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
