%% SDPE MATLAB initialization script
% Project: DPS FSBB F280039C IRIS Node
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Notes:
%   Four-switch buck-boost converter SDPE project requirement prepared from ctl/suite/dps_fsbb/project/f280039c_Iris_node/xplt/ctrl_settings.h.
%   The requirement introduces the GMP LVFB 150V 2-phase board as the switching stage and sensor source, and IRIS F280039C Node as the peripheral option provider.

%% Project metadata
DPS_FSBB_IRIS_SDPE_PROJECT_ID = 'dps_fsbb_f280039c_Iris_node';

DPS_FSBB_IRIS_SDPE_PROJECT_SUITE = 'dps_fsbb';

DPS_FSBB_IRIS_SDPE_PROJECT_VERSION = '0.1.0';

DPS_FSBB_IRIS_SDPE_PROJECT_UPDATED_AT = '2026-07-17';

%% Hardware macros
IRIS_F280039C_ID = 'iris_f280039c_node';

IRIS_F280039C_SCHEMA = 'iris_c2000_core_board';

IRIS_F280039C_NAME = 'IRIS F280039C Core Board';

% C2000 device name.
IRIS_F280039C_CHIP = 'TMS320F280039C';

% SysConfig source file used by this binding.
IRIS_F280039C_SYSCFG_FILE = 'ctl/suite/dps_fsbb/project/f280039c_Iris_node/F280039_Iris_node.syscfg';

% SysConfig EPWM1 base macro.
IRIS_F280039C_EPWM1_BASE = 'IRIS_EPWM1_BASE';

% SysConfig EPWM2 base macro.
IRIS_F280039C_EPWM2_BASE = 'IRIS_EPWM2_BASE';

% SysConfig ADC channel 1 macro.
IRIS_F280039C_ADC_CH1 = 'ADC_CH1';

% SysConfig ADC channel 2 macro.
IRIS_F280039C_ADC_CH2 = 'ADC_CH2';

% SysConfig ADC channel 3 macro.
IRIS_F280039C_ADC_CH3 = 'ADC_CH3';

% SysConfig ADC channel 4 macro.
IRIS_F280039C_ADC_CH4 = 'ADC_CH4';

%% Controller Settings
% Enable ADC calibration before normal control starts.
SPECIFY_ENABLE_ADC_CALIBRATE = true;

% ENABLE_GMP_DL_PIL_SIM is disabled in the SDPE project requirement.
% ENABLE_GMP_DL_PIL_SIM = true;

% GMP_CTL_FM_CONFIG_ENABLE_DEBUG_INFO is disabled in the SDPE project requirement.
% GMP_CTL_FM_CONFIG_ENABLE_DEBUG_INFO = true;

% Invert duty-to-CMP mapping because the IRIS ePWM action qualifier sets high on up-count CMPA and low on down-count CMPA.
PWM_MODULATOR_USING_NEGATIVE_LOGIC = 1;

% This macro will disable the fault request of the controller. That's dangerous.
DISABLE_FSBB_PROTECTION_FAULT_LOGIC = true;

%% Optional Sampling Channels
% FSBB_ENABLE_IOUT_SAMPLE is disabled in the SDPE project requirement.
% FSBB_ENABLE_IOUT_SAMPLE = true;

% FSBB_ENABLE_VIN_SAMPLE is disabled in the SDPE project requirement.
% FSBB_ENABLE_VIN_SAMPLE = true;

%% Controller Options
% Incremental debug build level. 1: modulation and hardware check; 2: current loop; 3: voltage loop.
% Options: (1), (2), (3)
BUILD_LEVEL = 1;

%% Board GPIO
% Gate-driver enable GPIO.
% Options: IRIS_GPIO1, IRIS_GPIO2, IRIS_GPIO3, IRIS_GPIO4, IRIS_GPIO5, IRIS_GPIO6
PWM_ENABLE_PORT = 'IRIS_GPIO1';

% Gate-driver reset GPIO.
% Options: IRIS_GPIO1, IRIS_GPIO2, IRIS_GPIO3, IRIS_GPIO4, IRIS_GPIO5, IRIS_GPIO6
PWM_RESET_PORT = 'IRIS_GPIO3';

% System status LED.
% Options: IRIS_LED1, IRIS_LED2, LED_R, LED_G
SYSTEM_LED = 'IRIS_LED1';

%% PWM Channel
% Buck phase ePWM base.
% Options: IRIS_EPWM1_BASE, IRIS_EPWM2_BASE, IRIS_EPWM3_BASE, IRIS_EPWM4_BASE, IRIS_EPWM5_BASE, IRIS_EPWM6_BASE
PHASE_BUCK_BASE = 'IRIS_EPWM1_BASE';

% Boost phase ePWM base.
% Options: IRIS_EPWM1_BASE, IRIS_EPWM2_BASE, IRIS_EPWM3_BASE, IRIS_EPWM4_BASE, IRIS_EPWM5_BASE, IRIS_EPWM6_BASE
PHASE_BOOST_BASE = 'IRIS_EPWM2_BASE';

%% ADC Channel
% Input voltage ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
FSBB_VIN_ADC_BASE = 'ADC_CH1_RESULT_BASE';

% Input voltage ADC channel index.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
FSBB_VIN = 'ADC_CH1';

% Output voltage ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
FSBB_VOUT_ADC_BASE = 'ADC_CH2_RESULT_BASE';

% Output voltage ADC channel index.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
FSBB_VOUT = 'ADC_CH2';

% Inductor current ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
FSBB_IL_ADC_BASE = 'ADC_CH3_RESULT_BASE';

% Inductor current ADC channel index.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
FSBB_IL = 'ADC_CH3';

% Input current ADC result register base, available when input-current sampling is enabled.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
FSBB_IIN_ADC_BASE = 'ADC_CH4_RESULT_BASE';

% Input current ADC channel index, available when input-current sampling is enabled.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
FSBB_IIN = 'ADC_CH4';

% Output/load current ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
FSBB_IOUT_ADC_BASE = 'ADC_CH5_RESULT_BASE';

% Output/load current ADC channel index.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
FSBB_IOUT = 'ADC_CH5';

%% Requirement bindings
% PWM compare maximum value for the configured ePWM time base.
CTRL_PWM_CMP_MAX = 3000 - 1;

% PWM deadband compare count.
CTRL_PWM_DEADBAND_CMP = 50;

% CPU main clock frequency.
CTRL_SYS_FREQUENCY = 120e6;

% C2000 system tick divider derived from PWM period.
DSP_C2000_DSP_TIME_DIV = CTRL_SYS_FREQUENCY / 1000 / CTRL_PWM_CMP_MAX / 2;

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
