%% SDPE MATLAB initialization script
% Project: DPS FSBB MATLAB/Simulink SIL
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

%% Project metadata
DPS_FSBB_SIM_SDPE_PROJECT_ID = 'dps_fsbb_simulate';

DPS_FSBB_SIM_SDPE_PROJECT_SUITE = 'dps_fsbb';

DPS_FSBB_SIM_SDPE_PROJECT_VERSION = '1.0.0';

DPS_FSBB_SIM_SDPE_PROJECT_UPDATED_AT = '2026-07-18';

%% Hardware macros
BSC093N15NS5_ID = 'bsc093n15ns5';

BSC093N15NS5_SCHEMA = 'power_switch';

BSC093N15NS5_NAME = 'BSC093N15NS5';

% Power device part number.
BSC093N15NS5_PART_NUMBER = 'BSC093N15NS5';

% MOSFET, IGBT, GaN, SiC, etc.
BSC093N15NS5_DEVICE_TYPE = 'MOSFET';

% Drain-source or collector-emitter voltage rating.
BSC093N15NS5_VOLTAGE_RATING_V = 150.0;

% Current rating.
BSC093N15NS5_CURRENT_RATING_A = 55.0;

% On resistance.
BSC093N15NS5_RDSON_OHM = 0.0093;

% Single switch, dual switch, half bridge power block, etc.
BSC093N15NS5_CONFIGURATION = 'single';

% Maximum on resistance at the documented gate voltage.
BSC093N15NS5_RDSON_MAX_OHM = 0.0;

% Gate voltage associated with the resistance value.
BSC093N15NS5_GATE_VOLTAGE_V = 0.0;

% Typical total gate charge.
BSC093N15NS5_GATE_CHARGE_NC = 0.0;

% Manufacturer package name.
BSC093N15NS5_PACKAGE = 'unknown';

TMCS1133_B5A_ID = 'tmcs1133_b5a';

TMCS1133_B5A_SCHEMA = 'current_sensor';

TMCS1133_B5A_NAME = 'TMCS1133 B5A Hall Current Sensor';

% Main sensing IC or technology name.
TMCS1133_B5A_CHIP = 'TMCS1133B5A';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TMCS1133_B5A_SENSOR_TYPE = 'Hall';

% Nominal measurable current range.
TMCS1133_B5A_RANGE_A = 10.3;

% Minimum output voltage.
TMCS1133_B5A_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TMCS1133_B5A_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TMCS1133_B5A_BIAS_V = 1.65;

% Current sensor sensitivity.
TMCS1133_B5A_SENSITIVITY_MV_PER_A = 150.0;

% Typical small-signal bandwidth.
TMCS1133_B5A_BANDWIDTH_HZ = 300000.0;

% Sensor internal series resistance.
TMCS1133_B5A_INTERNAL_RESISTANCE_OHM = 0.0018;

% Current sensor sensitivity converted to V/A.
TMCS1133_B5A_SENSITIVITY_V_PER_A = TMCS1133_B5A_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A = TMCS1133_B5A_BIAS_V / TMCS1133_B5A_SENSITIVITY_V_PER_A;

LVFB_VDIV_150V_ID = 'lvfb_voltage_divider_150v';

LVFB_VDIV_150V_SCHEMA = 'voltage_sensor';

LVFB_VDIV_150V_NAME = 'LVFB 150V Voltage Divider';

% Main sensing IC or front-end topology.
LVFB_VDIV_150V_CHIP = 'AMC1311BDWVR + resistor divider';

% Nominal measurable voltage.
LVFB_VDIV_150V_RATED_VOLTAGE_V = 150.0;

% Output bias voltage.
LVFB_VDIV_150V_BIAS_V = 0.0;

% Voltage sensor sensitivity.
LVFB_VDIV_150V_SENSITIVITY_V_PER_V = 0.016129;

% Equivalent input resistance.
LVFB_VDIV_150V_INPUT_RESISTANCE_OHM = 915000.0;

% Approximate positive full scale voltage when biased at mid-supply.
LVFB_VDIV_150V_MAX_BY_BIAS_V = sdpe_select(LVFB_VDIV_150V_BIAS_V > 0.0, LVFB_VDIV_150V_BIAS_V / LVFB_VDIV_150V_SENSITIVITY_V_PER_V, LVFB_VDIV_150V_RATED_VOLTAGE_V);

GMP_LVFB_ID = 'gmp_lvfb_150_2ph_v2';

GMP_LVFB_SCHEMA = 'half_bridge';

GMP_LVFB_NAME = 'GMP LVFB 150V 2-Phase V2 Inverter Board';

% Board or module name.
GMP_LVFB_BOARD_NAME = 'GMP LVFB 2ph V6.1';

% Integrated gate driver part number.
GMP_LVFB_GATE_DRIVER = 'UCC21520DWR';

% Power MOSFET part number.
GMP_LVFB_MOSFET = 'BSC093N15NS5';

% On-board current sensing device.
GMP_LVFB_CURRENT_SENSOR_NAME = 'TMCS1133B5A';

% On-board voltage sensing device.
GMP_LVFB_VOLTAGE_SENSOR_NAME = 'AMC1311BDWVR';

% Number of half-bridge phases represented by this module.
GMP_LVFB_PHASE_COUNT = 2;

% Current measurement range exported by the current sensor sub component.
GMP_LVFB_MEASURED_CURRENT_RANGE_A = TMCS1133_B5A_RANGE_A;

% Maximum allowable DC bus voltage.
GMP_LVFB_VBUS_MAX_V = 120.0;

% Maximum instantaneous peak phase current.
GMP_LVFB_CURRENT_MAX_PEAK_A = 55.0;

% Maximum continuous RMS phase current.
GMP_LVFB_CURRENT_MAX_RMS_A = 35.0;

% Recommended hardware deadtime.
GMP_LVFB_DEADTIME_NS = 523.0;

% Current sensing signal bandwidth.
GMP_LVFB_CURRENT_BW_HZ = 300.0e3;

% Current sensor ADC bias voltage.
GMP_LVFB_CURRENT_BIAS_V = 1.65;

% Configured current sensitivity.
GMP_LVFB_CURRENT_SENSITIVITY = TMCS1133_B5A_SENSITIVITY_V_PER_A;

% ADC reference scale voltage.
GMP_LVFB_VOLTAGE_BASE_V = 3.3;

% Voltage sensing ADC bias voltage.
GMP_LVFB_VOLTAGE_BIAS_V = 0.0;

% Voltage sensing bandwidth.
GMP_LVFB_VOLTAGE_BW_HZ = 114.47e3;

% Default low-side voltage divider resistance.
GMP_LVFB_VOLTAGE_R_LOW_OHM = 15000.0;

% Default high-side voltage divider resistance.
GMP_LVFB_VOLTAGE_R_HIGH_OHM = 300000.0;

% Configured voltage sensing gain.
GMP_LVFB_VOLTAGE_SENSITIVITY = (15e3) / ((15e3) + ((300e3) * 3)) * 1.65;

% Configured maximum measurable voltage.
GMP_LVFB_VOLTAGE_MAX = 3.3 / ((15e3) / ((15e3) + ((300e3) * 3)) * 1.65);

% Optional local DC bus capacitance.
GMP_LVFB_BUS_CAPACITANCE_F = 0.0;

% Whether this module declares a local bus capacitor.
GMP_LVFB_HAS_LOCAL_BUS_CAP = GMP_LVFB_BUS_CAPACITANCE_F > 0.0;

%% SIL
% SPECIFY_ENABLE_ADC_CALIBRATE is disabled in the SDPE project requirement.
% SPECIFY_ENABLE_ADC_CALIBRATE = true;

% ENABLE_GMP_DL_PIL_SIM is disabled in the SDPE project requirement.
% ENABLE_GMP_DL_PIL_SIM = true;

% Allow ENABLE_OPERATION to advance through the complete CiA402 startup sequence.
CIA402_CONFIG_ENABLE_SEQUENCE_SWITCH = true;

%% Sampling
% Use the simulated input-voltage ADC channel.
FSBB_ENABLE_VIN_SAMPLE = true;

% Use the simulated Boost-side output-current ADC channel.
FSBB_ENABLE_IOUT_SAMPLE = true;

%% PWM
% PWM_MODULATOR_USING_NEGATIVE_LOGIC is disabled in the SDPE project requirement.
% PWM_MODULATOR_USING_NEGATIVE_LOGIC = 1;

%% Controller Settings
% DISABLE_FSBB_PROTECTION_FAULT_LOGIC is disabled in the SDPE project requirement.
% DISABLE_FSBB_PROTECTION_FAULT_LOGIC = true;

%% Controller
% 1: open loop, 2: current loop, 3: voltage/current cascade.
% Options: (1), (2), (3)
BUILD_LEVEL = 3;

%% Requirement bindings
% PWM compare maximum shared by controller and plant model.
CTRL_PWM_CMP_MAX = 3000 - 1;

% Symmetric PWM deadband in compare counts.
CTRL_PWM_DEADBAND_CMP = 50;

% ADC resolution used by all simulated sensor channels.
CTRL_ADC_RESOLUTION = 12;

% Input capacitor ESR used by the plant.
FSBB_PARAM_CIN_ESR = 0.1;

% Buck-side input-current sensor sensitivity in V/A.
CTRL_FSBB_IIN_SENSITIVITY = GMP_LVFB_CURRENT_SENSITIVITY;

% Buck-side input-current sensor bias in V.
CTRL_FSBB_IIN_BIAS = GMP_LVFB_CURRENT_BIAS_V;

% BSC093N15NS5 nominal on resistance used by the plant.
FSBB_MODEL_MOSFET_RON = 9.3e-3;

% Plant-model snubber resistance.
FSBB_MODEL_SNUBBER_R = 1e5;

% Large plant-model snubber capacitance approximating an open capacitive branch.
FSBB_MODEL_SNUBBER_C = 1e12;

% MOSFET body-diode forward voltage.
FSBB_MODEL_DIODE_VF = 0.8;

% MOSFET body-diode on resistance.
FSBB_MODEL_DIODE_RON = 1e-3;

% Ideal-switch series inductance.
FSBB_MODEL_SWITCH_LON = 0;

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
